name: CI
on: push
jobs:
  build:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build encoder and decoder
        run: make install

      - name: Run test
        run: make test

      - name: Run encoder
        run: test "63OqKywk" = "$(make encode SALT=salt ID_LENGTH=8 SRC=100000)"
